name: Continuous Integration - Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install apt dependencies
        run: sudo apt-get install -y graphviz
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn -P native --batch-mode --update-snapshots verify
      - name: Deploy snapshots with Maven
        if: ${{ github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'chore(release)') }}
        run: mvn --batch-mode --update-snapshots deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy release with Maven
        if: ${{ startsWith(github.ref, 'refs/tags/') && startsWith(github.event.head_commit.message, 'chore(release)') }}
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish website
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/tutorial/target/generated-docs